services:
  - type: web
    name: pneumonia-detector
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd PneumoniaDetectorWebApp && gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
