services:
  - type: web
    name: pneumonia-detector
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: cd PneumoniaDetectorWebApp && gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 180 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
